// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "NeyurD%/J+z(+e+x[L]s_img":
            case "usagi":return img`
....................ffffffff......................
....................ffffffff......................
...................f555ff555f.....................
...................f553ff355f.....................
...................f553ff355f.....................
...................f553ff355f.....................
...................f553ff355f.....................
...................f553ff355f.....................
...................f553ff355f.....................
...................f553ff355f.....................
...................f553ff355f.....................
................fff5555555555fffff................
.............fff555555555555555555f...............
.............fff555555555555555555f...............
............f55555ffff555555ffff555f..............
............f555ff55555555555555ff55ff............
............f555ff55555555555555ff55ff............
..........ff555f555555555555555555f5ff............
..........ff555555555555555555555555ff............
..........ff555555555555555555555555ff............
..........ff555555f111555555f1115555ff............
..........ff555555ff11555555fff15555ff............
..........ff555555ff11555555fff15555ff............
..........ff5555551fff5555551fff5555ff............
..........ff533333555555555555553335ff............
..........ff533333555555555555553335ff............
..........ff53333355ff555f55f5553335ff............
..........ff5555555555fffffff5555555ff............
..........ff5555555555fffffff5555555ff............
............f5555555555555ff5555555f..............
.............fff5555555555555555fff...............
.............fff5555555555555555fff...............
................ffffffffffffffff..................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
`;
            case "image2":
            case "myImage":return img`
............................................................
............................................................
............................................................
............................................................
............................................................
.......................ffff....ffff.........................
.......................ffff....ffff.........................
.......................ffffffffffff.........................
.....................ffffffffffffffff.......................
....................ffffffffffffffffff......................
....................fffffffffffffffffff.....................
...................ffffffffffffffffffff.....................
..................ffffffffffffffffffffff....................
..................ffffffffffffffffffffff....................
..................ffffffffffffffffffffff....................
..................ffffffffffffffffffffff....................
..................ffffffffffffffffffffff....................
..................ffffffffffffffffffffff....................
..................ffffffffffffffffffffff....................
..................ffffffffffffffffffffff....................
..................ffffffffffffffffffffff....................
..................ffffffffffffffffffffff....................
...................ffffffffffffffffffff.....................
....................fffffffffffffffffff.....................
.....................ffffffffffffffff.......................
....................fffffffffffffffffff.....................
...................ffffffffffffffffffff.....................
...................fffffffffffffffffffff....................
..................ffffffffffffffffffffff....................
.................fffffffffffffffffffffffff..................
................fffffffffffffffffffffffffff.................
................fffffffffffffffffffffffffff.................
...............fffffffffffffffffffffffffffff................
...............fffffffffffffffffffffffffffff................
...............fffffffffffffffffffffffffffff................
..............ffffffffffffffffffffffffffffff................
..............ffffffffffffffffffffffffffffff................
..............ffffffffffffffffffffffffffffff................
..............ffffffffffffffffffffffffffffff................
..............ffffffffffffffffffffffffffffff................
..............ffffffffffffffffffffffffffffff................
..............ffffffffffffffffffffffffffffff................
..............ffffffffffffffffffffffffffffff................
...............fffffffffffffffffffffffffffff................
.................fffffffffffffffffffffff....................
.................fffffffffffffffffffffff....................
.................fffffffffffffffffffffff....................
.................fffffffffffffffffffffff....................
.................fffffffffffffffffffffff....................
..................fffffffffffffffffffff.....................
...................ffffffffffffffffffff.....................
...................ffffffffffffffffffff.....................
...................ffffffffffffffffffff.....................
...................ffffffffff..ffffffff.....................
...................ffffffffff..ffffffff.....................
...................fffffffff...ffffffff.....................
...................fffffffff...ffffffff.....................
...................fffffffff...ffffffff.....................
....................ffffffff...fffffff......................
....................fffffff.....ffffff......................
`;
            case "image1":
            case "Bunny":return img`
.......eee....eee.............
......e111e..ed13e............
......e1331e.ed13e............
......ed1331eed113e...........
.......ed1331eed13e...........
........ed1131eed13e..........
.........edd131ed11e..........
..........eed131ed11ee........
............e111111111e.......
..........ee11111111111e......
..........ed111111111111e.....
.........ed11111111111111e....
.........ed11111111111111e....
.........ed111111111111b1e....
.........ed11111b111111c1e....
.........edd1111c111111f1e....
.........edd1111f11113113e....
..........edd133111111111e....
.........eeedd111111111ee.....
.......eed1111111111dee.......
...ee.edd111111111111de.......
..e11eed11111111111111e.......
..ed1edd11111111111111de......
..ed1ed11111111111111dde......
..edded111111111d11dddde......
...eeed1111111111dddddde......
.....ed111eeddd111eedde.......
.....edd1111eeddd111eede......
......edd11111eeed11e11e......
.......eeeeeeee..eeeeee.......
`;
            case "image3":
            case "Bunny0":return img`
.......fff....fff.............
......fbbbf..fcb3f............
......fb33bf.fcb3f............
......fcb33bffcbb3f...........
.......fcb33bffcb3f...........
........fcbb3bffcb3f..........
.........fccb3bfcbbf..........
..........ffcb3bfcbbff........
............fbbbbbbbbbf.......
..........ffbbbbbbbbbbbf......
..........fcbbbbbbbbbbbbf.....
.........fcbbbbbbbbbbbbbbf....
.........fcbbbbbbbbbbbbbbf....
.........fcbbbbbbbbbbbbdbf....
.........fcbbbbbdbbbbbbcbf....
.........fccbbbbcbbbbbbfbf....
.........fccbbbbfbbbb3bb3f....
..........fccb33bbbbbbbbbf....
.........fffccbbbbbbbbbff.....
.......ffcbbbbbbbbbbcff.......
...ff.fccbbbbbbbbbbbbcf.......
..fbbffcbbbbbbbbbbbbbbf.......
..fcbfccbbbbbbbbbbbbbbcf......
..fcbfcbbbbbbbbbbbbbbccf......
..fccfcbbbbbbbbbcbbccccf......
...fffcbbbbbbbbbbccccccf......
.....fcbbbffcccbbbffccf.......
.....fccbbbbffcccbbbffcf......
......fccbbbbbfffcbbfbbf......
.......ffffffff..ffffff.......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
